### PR TITLE
fixes #247: Schema Ingestion Strategy: double node creation

### LINKED ISSUE #247: Schema Ingestion Strategy: double node creation
### How to reproduce the problem

Using the following script
```cypher
CREATE CONSTRAINT ON (m:Movie) ASSERT m.id IS UNIQUE;
CREATE CONSTRAINT ON (p:Person) ASSERT p.id IS UNIQUE;
CREATE INDEX ON :Person(name);
CREATE INDEX ON :Movie(title);

USING PERIODIC COMMIT 40000
LOAD CSV WITH HEADERS FROM "http://data.neo4j.com/advanced/movies/new_movies.csv" AS row
CREATE (:Movie {id: toInteger(row.movieId), released: toInteger(row.releaseYear), title: row.title, avgvote: toFloat(row.avgVote), genres: split(row.genres,':')});

USING PERIODIC COMMIT 40000
LOAD CSV WITH HEADERS FROM "http://data.neo4j.com/advanced/movies/people.csv" AS row
CREATE (:Person {id: toInteger(row.personId), name: row.name, birthyear: toInteger(row.birthYear), deathyear: toInteger(row.deathYear)});

USING PERIODIC COMMIT 40000
LOAD CSV WITH HEADERS FROM "http://data.neo4j.com/advanced/movies/directors.csv" AS row
MATCH (m:Movie {id: toInteger(row.movieId)})
MATCH (p:Person {id: toInteger(row.personId)})
MERGE (p)-[:DIRECTED]->(m)
SET p:Director;

USING PERIODIC COMMIT 40000
LOAD CSV WITH HEADERS FROM "http://data.neo4j.com/advanced/movies/actors.csv" AS row
MATCH (m:Movie {id: toInteger(row.movieId)})
MATCH (p:Person {id: toInteger(row.personId)})
MERGE (p)-[a:ACTED_IN]->(m)
SET a.roles = split(row.characters, ":")
SET p:Actor;
```

In particular the double node creation happens when we create the relationships because of these two `SET p:Director;` and `SET p:Actor` operations (without them the import goes well).
Because this kind of relationship event gets generated:

```json
{
  "meta":{"timestamp":1569254379576,"username":"neo4j","txId":39,"txEventId":20409,"txEventsCount":20410,"operation":"created","source":{"hostname":"neo4j-source"}},
  "payload":{"id":"47979","start":{"id":"10215","labels":["Person","Actor"],"ids":{"id":18365}},"end":{"id":"1761","labels":["Movie"],"ids":{"id":396}},"before":null,"after":{"properties":{"roles":["Honey"]}},"label":"ACTED_IN","type":"relationship"},
  "schema":{"properties":{"roles":"String[]"},"constraints":[{"label":"Person","properties":["id"],"type":"UNIQUE"},{"label":"Movie","properties":["id"],"type":"UNIQUE"}]}
}
```

The `labels` field for the person contains also the new label `"labels":["Person","Actor"]`,
and the schema strategy leverages that labels to build the cypher query.

### Possibile solution

Add into the `schema` field the constraints related to the nodes involved in the relationship, so we can use that information in the ingestion strategy to filter the labels in according to the labels.

### PR DESCRIPTION
**Pull request by conker84**
Fixes #247
Fixed the bug

## Proposed Changes (Mandatory)

A brief list of proposed changes in order to fix the issue:

  - Added the schema information about start/end nodes into the relationship schema event
  - Updated the Schema ingestion strategy in order to leverage the new schema information

### CODE REVIEW

File: common/src/main/kotlin/streams/service/sink/strategy/SchemaIngestionStrategy.kt [hunk 1]
```diff
@@ -2,38 +2,63 @@ package streams.service.sink.strategy
...
+                }
+                val endNodeConstraints = getNodeConstraints(it) {
+                    it.type == StreamsConstraintType.UNIQUE && payload.end.labels.orEmpty().contains(it.label)
                 }
 
-                key to value
+                if (startNodeConstraints.isEmpty() || endNodeConstraints.isEmpty()) {
+                    null
+                } else {
+                    val startNodeKeys = getNodeKeys(
```
Comment (jexp) [inline common/src/main/kotlin/streams/service/sink/strategy/SchemaIngestionStrategy.kt]: can you extract this into a sensible method

Comment (conker84) [reply common/src/main/kotlin/streams/service/sink/strategy/SchemaIngestionStrategy.kt]: done!
