### PR TITLE
fixes #108 (StreamTopicService error in cluster environment at startup) / #109 (Error when Neo4j server shutdown) / #111 (streams.consume procedure consumes just maps messages)

### LINKED ISSUE #108: StreamTopicService error in cluster environment at startup
the `StreamTopicService` in cluster environment, at the startup, tries to delete graph properties also in followers and read replicas

### LINKED ISSUE #109: Error when Neo4j server shutdown
Thanks to  @lju-lazarevic for reporting this

```
2018-12-21 10:53:32.436+0000 INFO  Neo4j Server shutdown initiated by request
2018-12-21 10:53:32.491+0000 INFO  Stopping...
Terminate batch job (Y/N)? 2018-12-21 10:53:32.564+0000 INFO  Stopping Sink daemon Job
2018-12-21 10:53:32.565+0000 ERROR KafkaConsumer is not safe for multi-threaded access KafkaConsumer is not safe for multi-threaded access
java.util.ConcurrentModificationException: KafkaConsumer is not safe for multi-threaded access
        at org.apache.kafka.clients.consumer.KafkaConsumer.acquire(KafkaConsumer.java:1808)
        at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:1701)
        at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:1680)
        at streams.kafka.KafkaEventConsumer$stop$1.invoke(KafkaEventSink.kt:121)
        at streams.kafka.KafkaEventConsumer$stop$1.invoke(KafkaEventSink.kt:100)
        at streams.utils.StreamsUtils.ignoreExceptions(StreamsUtils.kt:13)
        at streams.kafka.KafkaEventConsumer.stop(KafkaEventSink.kt:121)
        at streams.kafka.KafkaEventSink.stop(KafkaEventSink.kt:61)
        at streams.StreamsEventSinkExtensionFactory$StreamsEventLifecycle$stop$1.invoke(StreamsEventSinkExtensionFactory.kt:63)
        at streams.StreamsEventSinkExtensionFactory$StreamsEventLifecycle$stop$1.invoke(StreamsEventSinkExtensionFactory.kt:27)
        at streams.utils.StreamsUtils.ignoreExceptions(StreamsUtils.kt:13)
        at streams.StreamsEventSinkExtensionFactory$StreamsEventLifecycle.stop(StreamsEventSinkExtensionFactory.kt:63)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:480)
        at org.neo4j.kernel.lifecycle.LifeSupport.stopInstances(LifeSupport.java:161)
        at org.neo4j.kernel.lifecycle.LifeSupport.stop(LifeSupport.java:143)
        at org.neo4j.kernel.extension.KernelExtensions.stop(KernelExtensions.java:90)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:480)
        at org.neo4j.kernel.lifecycle.LifeSupport.stopInstances(LifeSupport.java:161)
        at org.neo4j.kernel.lifecycle.LifeSupport.stop(LifeSupport.java:143)
        at org.neo4j.kernel.lifecycle.LifeSupport.shutdown(LifeSupport.java:191)
        at org.neo4j.kernel.impl.factory.ClassicCoreSPI.shutdown(ClassicCoreSPI.java:180)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.shutdown(GraphDatabaseFacade.java:364)
        at org.neo4j.server.database.LifecycleManagingDatabase.stop(LifecycleManagingDatabase.java:105)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:480)
        at org.neo4j.kernel.lifecycle.LifeSupport.stopInstances(LifeSupport.java:161)
        at org.neo4j.kernel.lifecycle.LifeSupport.stop(LifeSupport.java:143)
        at org.neo4j.server.AbstractNeoServer.stop(AbstractNeoServer.java:392)
        at org.neo4j.server.ServerBootstrapper.lambda$addShutdownHook$4(ServerBootstrapper.java:226)
        at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by conker84**
Fixes #108, #109, #111 

This PR fixes the three issues.

## Proposed Changes (Mandatory)

A brief list of proposed changes in order to fix the issue:

  - added `Neo4jUtils.isWriteableInstance` where necessary
  - in order to fix #109 we reduced the poll interval to 10 seconds (this is an intermediate solution), the next step is providing #102
  - the `streams.consume` procedure now is able consume messages like `[{"name": "Andrea", "surname": "Santurbano"}, {"name": "Michael", "surname": "Hunger"}]`, moreover a better failure management is provided

### CODE REVIEW

File: consumer/src/main/kotlin/streams/StreamsEventSinkQueryExecution.kt [hunk 1]
```diff
@@ -14,12 +13,16 @@ class StreamsEventSinkQueryExecution(private val streamsTopicService: StreamsTop
             return
         }
         val query = "${StreamsUtils.UNWIND} $cypherQuery"
-        if(log.isDebugEnabled){
+        if (log.isDebugEnabled) {
             log.debug("Processing ${params.size} events with query: $query")
```
Comment (jexp) [inline consumer/src/main/kotlin/streams/StreamsEventSinkQueryExecution.kt]: should we also output the topic?

File: consumer/src/main/kotlin/streams/procedures/StreamsSinkProcedures.kt [hunk 2]
```diff
@@ -1,22 +1,21 @@
...
+class StreamResult(@JvmField val event: Map<String, *>)
 
 class StreamsSinkProcedures {
 
     @JvmField @Context
     var log: Log? = null
 
     @Procedure(mode = Mode.SCHEMA, name = "streams.consume")
-    @Description("streams.consume(topic, config) - Allows to subscribe custom topics")
+    @Description("streams.consume(topic, config) YIELD event - Allows to consume custom topics")
```
Comment (jexp) [inline consumer/src/main/kotlin/streams/procedures/StreamsSinkProcedures.kt]: perhaps at least add the config keys in the description

File: consumer/src/main/kotlin/streams/StreamsEventSinkQueryExecution.kt (hunk 1 above)
Comment (conker84) [reply consumer/src/main/kotlin/streams/StreamsEventSinkQueryExecution.kt]: Done!

File: consumer/src/main/kotlin/streams/procedures/StreamsSinkProcedures.kt (hunk 2 above)
Comment (conker84) [reply consumer/src/main/kotlin/streams/procedures/StreamsSinkProcedures.kt]: Done!
