### PR TITLE
Fixes #64: Minor fixes in Consumer

### LINKED ISSUE #64: Minor fixes in Consumer
- Improved logging
- Fixed Typos
- Removed some compile warning after moving to 1.3

### PR DESCRIPTION
**Pull request by conker84**

### CODE REVIEW

File: consumer/src/main/kotlin/streams/kafka/KafkaEventSink.kt [hunk 1]
```diff
@@ -82,7 +87,7 @@ class KafkaEventSink: StreamsEventSink {
                                 .mapKeys { it.key.toString() }
                     }
             if (list.isNotEmpty()) {
-                log.debug("Sending data to topic $it, with data $list")
+                log.debug("Reading data from topic $it, with data $list")
```
Comment (jexp) [inline consumer/src/main/kotlin/streams/kafka/KafkaEventSink.kt]: can we wrap all the log.debug calls in the codebase with `log.isDebugEnabled()` ?
