### PR TITLE
 fixes #181: Validate configuration before attempting to start

### LINKED ISSUE #181: Validate configuration before attempting to start
When given an empty config, you get this error on startup.

This error is fairly difficult to debug because it doesn't say anything, but its root cause is:

```
kafka.bootstrap.servers=
```

```
May 24 17:29:31 supermax-core-vm-3 pre-neo4j.sh[10722]: 2019-05-24 17:29:31.238+0000 INFO  Initializing Kafka Connector
May 24 17:29:34 supermax-core-vm-3 pre-neo4j.sh[10722]: 2019-05-24 17:29:34.047+0000 INFO  Initialising the Streams Source module
May 24 17:29:34 supermax-core-vm-3 pre-neo4j.sh[10722]: org.apache.kafka.common.KafkaException: Failed to construct kafka producer
May 24 17:29:34 supermax-core-vm-3 pre-neo4j.sh[10722]:         at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:441)
May 24 17:29:34 supermax-core-vm-3 pre-neo4j.sh[10722]:         at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:297)
May 24 17:29:34 supermax-core-vm-3 pre-neo4j.sh[10722]:         at streams.kafka.Neo4jKafkaProducer.<init>(KafkaEventRouter.kt:103)
May 24 17:29:34 supermax-core-vm-3 pre-neo4j.sh[10722]:         at streams.kafka.KafkaEventRouter.start(KafkaEventRouter.kt:36)
May 24 17:29:34 supermax-core-vm-3 pre-neo4j.sh[10722]:         at streams.StreamsEventRouterLifecycle.start(StreamsExtensionFactory.kt:41)
May 24 17:29:34 supermax-core-vm-3 pre-neo4j.sh[10722]:         at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
May 24 17:29:34 supermax-core-vm-3 pre-neo4j.sh[10722]:         at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
May 24 17:29:34 supermax-core-vm-3 pre-neo4j.sh[10722]:         at org.neo4j.kernel.extension.AbstractKernelExtensions.start(AbstractKernelExtensions.java:82)
May 24 17:29:34 supermax-core-vm-3 pre-neo4j.sh[10722]:         at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
May 24 17:29:34 supermax-core-vm-3 pre-neo4j.sh[10722]:         at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
May 24 17:29:34 supermax-core-vm-3 pre-neo4j.sh[10722]:         at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
May 24 17:29:34 supermax-core-vm-3 pre-neo4j.sh[10722]:         at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
May 24 17:29:34 supermax-core-vm-3 pre-neo4j.sh[10722]:         at org.neo4j.kernel.NeoStoreDataSource.start(NeoStoreDataSource.java:434)
May 24 17:29:34 supermax-core-vm-3 pre-neo4j.sh[10722]:         at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
May 24 17:29:34 supermax-core-vm-3 pre-neo4j.sh[10722]:         at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
May 24 17:29:34 supermax-core-vm-3 pre-neo4j.sh[10722]:         at org.neo4j.kernel.impl.transaction.state.DataSourceManager.start(DataSourceManager.java:116)
May 24 17:29:34 supermax-core-vm-3 pre-neo4j.sh[10722]:         at org.neo4j.causalclustering.catchup.storecopy.LocalDatabase.start(LocalDatabase.java:86)
May 24 17:29:34 supermax-core-vm-3 pre-neo4j.sh[10722]:         at org.neo4j.causalclustering.core.state.CoreLife.start0(CoreLife.java:80)
May 24 17:29:34 supermax-core-vm-3 pre-neo4j.sh[10722]:         at org.neo4j.kernel.lifecycle.SafeLifecycle.transition(SafeLifecycle.java:124)
```

### PR DESCRIPTION
**Pull request by conker84**
Fixes #181 (we need to close this after #211 )

We validate some configuration params ensuring that the missing of these params will not affect the correct DB start-up. Following an example log in case the endpoint in `kafka.bootstrap.servers` param is not reachable:

```
neo4j              | 2019-07-25 13:29:02.019+0000 INFO  Kafka Connector started
neo4j              | 2019-07-25 13:29:02.024+0000 INFO  Streams Source module initialised
neo4j              | 2019-07-25 13:29:02.290+0000 INFO  Initialising the Streams Sink module
neo4j              | 2019-07-25 13:29:04.817+0000 INFO  Starting the Kafka Sink
neo4j              | 2019-07-25 13:29:04.932+0000 WARN  The Kafka Sink cannot be started because of this exception: The servers defined into the property `kafka.bootstrap.servers` are not reachable: [localhost:9092]
neo4j              | java.lang.RuntimeException: The servers defined into the property `kafka.bootstrap.servers` are not reachable: [localhost:9092]
neo4j              |    at streams.kafka.KafkaSinkConfigurationKt.validateConnection(KafkaSinkConfiguration.kt:38)
neo4j              |    at streams.kafka.KafkaSinkConfigurationKt.validateConnection$default(KafkaSinkConfiguration.kt:32)
neo4j              |    at streams.kafka.KafkaSinkConfiguration$Companion.validate(KafkaSinkConfiguration.kt:92)
neo4j              |    at streams.kafka.KafkaSinkConfiguration$Companion.from(KafkaSinkConfiguration.kt:61)
neo4j              |    at streams.kafka.KafkaEventSink$getEventConsumerFactory$1.createStreamsEventConsumer(KafkaEventSink.kt:40)
neo4j              |    at streams.kafka.KafkaEventSink.start(KafkaEventSink.kt:73)
neo4j              |    at streams.StreamsEventSinkExtensionFactory$StreamsEventLifecycle.initSinkModule(StreamsEventSinkExtensionFactory.kt:86)
neo4j              |    at streams.StreamsEventSinkExtensionFactory$StreamsEventLifecycle.access$initSinkModule(StreamsEventSinkExtensionFactory.kt:31)
neo4j              |    at streams.StreamsEventSinkExtensionFactory$StreamsEventLifecycle$start$1$available$2.invoke(StreamsEventSinkExtensionFactory.kt:68)
neo4j              |    at streams.StreamsEventSinkExtensionFactory$StreamsEventLifecycle$start$1$available$2.invoke(StreamsEventSinkExtensionFactory.kt:41)
neo4j              |    at streams.utils.Neo4jUtils.executeInWriteableInstance(Neo4jUtils.kt:76)
neo4j              |    at streams.StreamsEventSinkExtensionFactory$StreamsEventLifecycle$start$1.available(StreamsEventSinkExtensionFactory.kt:68)
neo4j              |    at org.neo4j.helpers.Listeners.notifySingleListener(Listeners.java:145)
neo4j              |    at org.neo4j.helpers.Listeners.notify(Listeners.java:101)
neo4j              |    at org.neo4j.kernel.availability.DatabaseAvailabilityGuard.fulfill(DatabaseAvailabilityGuard.java:90)
neo4j              |    at org.neo4j.kernel.availability.DatabaseAvailability.start(DatabaseAvailability.java:59)
neo4j              |    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
neo4j              |    at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
neo4j              |    at org.neo4j.kernel.NeoStoreDataSource.start(NeoStoreDataSource.java:444)
neo4j              |    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
neo4j              |    at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
neo4j              |    at org.neo4j.kernel.impl.transaction.state.DataSourceManager.start(DataSourceManager.java:116)
neo4j              |    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
neo4j              |    at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
neo4j              |    at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:225)
neo4j              |    at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:146)
neo4j              |    at org.neo4j.server.database.CommunityGraphFactory.newGraphDatabase(CommunityGraphFactory.java:41)
neo4j              |    at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:90)
neo4j              |    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
neo4j              |    at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
neo4j              |    at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:180)
neo4j              |    at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:124)
neo4j              |    at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:91)
neo4j              |    at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
neo4j              | 2019-07-25 13:29:23.802+0000 INFO  Bolt enabled on 0.0.0.0:7687.
neo4j              | 2019-07-25 13:29:25.214+0000 INFO  Started.
```

## Proposed Changes (Mandatory)

A brief list of proposed changes in order to fix the issue:

  - Added the validation

### CODE REVIEW

**Comment by mneedham** [comment]
This looks fine, but the PR also contains the AVRO stuff.

**Comment by mneedham** [comment]
@conker84 can we take the AVRO commit out of this PR?

**Comment by jexp** [comment]
@conker84 ping abou this one?

File: common/src/test/kotlin/streams/utils/ValidationUtilsTest.kt [hunk 1]
```diff
@@ -0,0 +1,36 @@
+package streams.utils
```
Comment (jexp) [inline common/src/test/kotlin/streams/utils/ValidationUtilsTest.kt]: Cool solution :)

File: consumer/src/main/kotlin/streams/StreamsEventSinkExtensionFactory.kt [hunk 2]
```diff
@@ -37,54 +37,52 @@ class StreamsEventSinkExtensionFactory : KernelExtensionFactory<StreamsEventSink
...
+                            eventSink = StreamsEventSinkFactory
+                                    .getStreamsEventSink(configuration,
+                                            streamsQueryExecution,
+                                            streamsTopicService,
+                                            log,
+                                            db)
+                            // start the Sink
+                            if (Neo4jUtils.isCluster(db)) {
+                                log.info("The Sink module is running in a cluster, checking for the ${Neo4jUtils.LEADER}")
+                                Neo4jUtils.waitForTheLeader(db, log) { initSinkModule(streamsTopicService, streamsSinkConfiguration) }
```
Comment (jexp) [inline consumer/src/main/kotlin/streams/StreamsEventSinkExtensionFactory.kt]: this is at startup, how do we do here with leader switches? if the sink module is not initialized on the non-leaders?

File: consumer/src/main/kotlin/streams/kafka/KafkaSinkConfiguration.kt [hunk 3]
```diff
@@ -71,7 +77,14 @@ data class KafkaSinkConfiguration(val zookeeperConnect: String = "localhost:2181
             )
         }
 
-        private fun validate(config: Map<String, String>) {
+        private fun validate(config: KafkaSinkConfiguration) {
+            validateConnection(config.zookeeperConnect, "zookeeper.connect", false)
+            validateConnection(config.bootstrapServers, CommonClientConfigs.BOOTSTRAP_SERVERS_CONFIG)
```
Comment (jexp) [inline consumer/src/main/kotlin/streams/kafka/KafkaSinkConfiguration.kt]: do all need to be reachable or just one?

File: producer/src/main/kotlin/streams/StreamsExtensionFactory.kt [hunk 4]
```diff
@@ -69,13 +69,17 @@ class StreamsEventRouterLifecycle(val db: GraphDatabaseAPI, val streamHandler: S
 
     private fun unregisterTransactionEventHandler() {
         if (streamsEventRouterConfiguration.enabled) {
-            streamsConstraintsService.close()
+            if (::streamsConstraintsService.isInitialized) {
```
Comment (jexp) [inline producer/src/main/kotlin/streams/StreamsExtensionFactory.kt]: this feels not right to have a static information
esp. in 4.0 with multi db this will fail as each db has it's own copy then
better to create an instance of: streamsConstraintsService
and have close be a no-op if the service is not initialized.

File: producer/src/main/kotlin/streams/StreamsExtensionFactory.kt [hunk 5]
```diff
@@ -69,13 +69,17 @@ class StreamsEventRouterLifecycle(val db: GraphDatabaseAPI, val streamHandler: S
...
+                streamsConstraintsService.close()
+            }
             db.unregisterTransactionEventHandler(txHandler)
         }
     }
 
     override fun stop() {
         unregisterTransactionEventHandler()
-        streamHandler.stop()
+        if (::streamHandler.isInitialized) {
```
Comment (jexp) [inline producer/src/main/kotlin/streams/StreamsExtensionFactory.kt]: same here

File: producer/src/main/kotlin/streams/kafka/KafkaEventRouter.kt [hunk 6]
```diff
@@ -22,24 +22,26 @@ import java.util.concurrent.ThreadLocalRandom
...
+        kafkaConfig = KafkaConfiguration.from(config?.raw ?: emptyMap())
         val props = kafkaConfig.asProperties()
         producer = Neo4jKafkaProducer<String, ByteArray>(props)
         producer.initTransactions()
         log.info("Kafka Connector started")
     }
 
     override fun stop() {
-        producer.close()
+        if (::producer.isInitialized) {
```
Comment (jexp) [inline producer/src/main/kotlin/streams/kafka/KafkaEventRouter.kt]: same here with the static initialization.

File: consumer/src/main/kotlin/streams/StreamsEventSinkExtensionFactory.kt (hunk 2 above)
Comment (conker84) [reply consumer/src/main/kotlin/streams/StreamsEventSinkExtensionFactory.kt]: this only waits for the leader election and then executes the `initSinkModule` on all cluster members.
Maybe we can do this better:
https://github.com/neo4j-contrib/neo4j-streams/blob/599a0813a456c89d741b6822f36a2d31916de2a5/consumer/src/main/kotlin/streams/StreamsEventSinkExtensionFactory.kt#L82-L85

by executing line 83/84 in only in a writeable instance?

File: consumer/src/main/kotlin/streams/kafka/KafkaSinkConfiguration.kt (hunk 3 above)
Comment (conker84) [reply consumer/src/main/kotlin/streams/kafka/KafkaSinkConfiguration.kt]: Kafka uses Zookeeper so we only need that the Kafka broker is reachable

File: producer/src/main/kotlin/streams/StreamsExtensionFactory.kt (hunk 4 above)
Comment (conker84) [reply producer/src/main/kotlin/streams/StreamsExtensionFactory.kt]: perfect

File: producer/src/main/kotlin/streams/StreamsExtensionFactory.kt (hunk 5 above)
Comment (conker84) [reply producer/src/main/kotlin/streams/StreamsExtensionFactory.kt]: ok

File: producer/src/main/kotlin/streams/kafka/KafkaEventRouter.kt (hunk 6 above)
Comment (conker84) [reply producer/src/main/kotlin/streams/kafka/KafkaEventRouter.kt]: ok

File: consumer/src/main/kotlin/streams/StreamsEventSinkExtensionFactory.kt (hunk 2 above)
Comment (jexp) [reply consumer/src/main/kotlin/streams/StreamsEventSinkExtensionFactory.kt]: would it wait forever? so possibly blocking the db startup for the non-leader members?
Or what happens on the non-leaders?

I guess starting it on the writeable instances makes sense.

Comment (conker84) [reply consumer/src/main/kotlin/streams/StreamsEventSinkExtensionFactory.kt]: No, it only checks if a leader is elected, as you underscored we need to start the plugin in all instance otherwise in case of rebalancing, it could not work; this means that the `eventSink.start()` must happen in all instances. We need to do that because of the lack of a trigger in changing of cluster role.

Comment (jexp) [reply consumer/src/main/kotlin/streams/StreamsEventSinkExtensionFactory.kt]: +1
