### PR TITLE
Fixes #305: CDC and Kafka Log Compaction

### LINKED ISSUE #305: CDC and Kafka Log Compaction
Hi everyone !! This issue is somehow similar to this one  #272 but the focus here is on Neo4j Streams Source for CDC in tandem with Kafka Log Compaction rather than on Neo4j Streams Procedures.

When using Change Data Capture with Kafka, one of the most common use cases is managing Kafka partitions as logs. In this scenario, Log Compaction is somehow necessary for CDC: we need a complete dataset but we must also avoid unlimited growth in the size of partitions. From the Kafka documentation:

> **Log compaction** ensures that Kafka will always retain at least the last known value for each message key within the log of data for a single topic partition. It **addresses use cases and scenarios such as restoring state after application crashes or system failure or reloading caches after application restarts during operational maintenance.**

On data retention:

> So far we have described only the simpler approach to data retention where old log data is discarded after a fixed period or when the log reaches some predetermined size. **This works well for temporal event data** such as logging **where each record stands alone. However, an important class of data streams are the log of changes to keyed, mutable data (for example, the changes to a database table).**

The current implementation of Neo4j Streams prevents this use cases since the message key is a combination of the transaction id and the id of the event inside the transaction, as shown in the following code ([KafkaEventRouter.kt](https://github.com/neo4j-contrib/neo4j-streams/blob/3.5/producer/src/main/kotlin/streams/kafka/KafkaEventRouter.kt)- line 86 - **sendEvent**  method):
```
private fun sendEvent(partition: Int, topic: String, event: StreamsTransactionEvent) {
        if (log.isDebugEnabled) {
            log.debug("Trying to send a transaction event with txId ${event.meta.txId} and txEventId ${event.meta.txEventId} to kafka")
        }
        val producerRecord = ProducerRecord(topic, partition, System.currentTimeMillis(), 
                 "${event.meta.txId + event.meta.txEventId}-${event.meta.txEventId}",
                JSONUtils.writeValueAsBytes(event))
        send(producerRecord)
    }
```
As far as I know, this will generate a sequence of unique keys, preventing Log Compaction. Instead, choosing the node or relationship id as the message key (``"${event.payload.id}"``) would enable Log Compaction on the Kafka side. However, I'm pretty sure there are specific reasons for creating the key that way: maybe the message keys are used to know where we are in the Neo4j log, to recover after a failure, but I'm not sure.

Can you explain why the keys are generated in this way? Is it possible to enable Log Compaction in Neo4j Streams right now? If the answer is no, I think this is a must-have feature for Change Data Capture. Thanks !!

## Considered alternatives

While writing this issue, I actually came up with a possible alternative solution (the same also applies to the issue #304): one can simply create a microservice using Kafka Streams to add custom logic and cope with order guarantees and log compaction. However, I am still convinced that these problems should be addressed within Neo4j Streams.

### PR DESCRIPTION
**Pull request by vga91**
Fixes #305

### CODE REVIEW

File: producer/src/main/kotlin/streams/Extensions.kt [hunk 1]
```diff
@@ -41,4 +42,35 @@ fun ConstraintDefinition.isNodeConstraint(): Boolean {
...
+
+fun StreamsTransactionEvent.asSourceRecordValue(strategy: String): StreamsTransactionEvent? =
+        if(isStrategyCompact(strategy) && meta.operation == OperationType.deleted) null else this
+
+fun StreamsTransactionEvent.asSourceRecordKey(strategy: String): Any =
+        when {
+            strategy == TopicConfig.CLEANUP_POLICY_DELETE -> "${meta.txId + meta.txEventId}-${meta.txEventId}"
+            isStrategyCompact(strategy) && payload is NodePayload -> getKeyOfNode(payload as NodePayload, schema)
+            isStrategyCompact(strategy) && payload is RelationshipPayload -> getKeyOfRel(payload as RelationshipPayload)
+            else -> throw RuntimeException("Invalid kafka.streams.log.compaction.strategy value: $strategy")
```
Comment (moxious) [inline producer/src/main/kotlin/streams/Extensions.kt:55]: This is a runtime error of a problem that should be detectable at configure time.

Can you please eliminate this thrown error message, which will spam every time something is sent over kafka (correct?)

Actual behavior should be that when you specify a bad config `kafka.streams.log.compaction.strategy=(╯°□°）╯︵ ┻━┻` that the plugin at start time should say "Invalid log compaction strategy setting, switching to default value XYZ" and then at runtime use the correct default.

File: doc/docs/modules/ROOT/pages/producer-configuration.adoc [hunk 2]
```diff
@@ -45,6 +46,12 @@ You can tune the custom property `kafka.topic.discovery.polling.interval` in ord
 periodically check for new topics into the Kafka cluster so the plugin will be able
 to send events to the defined topics.
 
+
+With `kafka.streams.log.compaction.strategy=delete` will be generated a sequence of unique keys with Neo4j Streams Source.
+instead with `kafka.streams.log.compaction.strategy=compact` the keys will be adapted to enable
+https://kafka.apache.org/documentation.html#compaction[Log Compaction] on the Kafka side.
+Namely, the operations which will involve the same nodes or relationships, will have the same key.
```
Comment (moxious) [inline doc/docs/modules/ROOT/pages/producer-configuration.adoc:53]: State what the default is if you don't choose, which will be most users.    Line above suggests that it's delete?

Also, why do we call it delete?  This sounds like something's getting deleted....now when logs get compacted to 500mb (or whatever) that's probably true, things get deleted.  But maybe this should be called "unique" or something?  (Because the IDs end up unique and not compact-able) I'm not sure.  Which is the least confusing for users?

File: producer/src/main/kotlin/streams/kafka/KafkaConfiguration.kt [hunk 3]
```diff
@@ -28,6 +29,7 @@ data class KafkaConfiguration(val zookeeperConnect: String = "localhost:2181",
                               val transactionalId: String = StringUtils.EMPTY,
                               val lingerMs: Int = 1,
                               val topicDiscoveryPollingInterval: Long = TimeUnit.MINUTES.toMillis(5),
+                              val streamsLogCompactionStrategy: String = TopicConfig.CLEANUP_POLICY_DELETE,
```
Comment (moxious) [inline producer/src/main/kotlin/streams/kafka/KafkaConfiguration.kt:32]: ah, there's the default.  It's fine to pick whichever default you wish (best to keep it the way it's been in the past for compatibility reasons).  See note earlier about naming / delete

File: producer/src/test/kotlin/streams/integrations/KafkaEventRouterLogCompactionTSE.kt [hunk 4]
```diff
@@ -0,0 +1,627 @@
...
+        db.execute("CALL streams.publish('$topic', 'Compaction 2', {key: '$keyRecord'})")
+        db.execute("CALL streams.publish('$topic', 'Compaction 3', {key: 'Foo'})")
+        db.execute("CALL streams.publish('$topic', 'Compaction 4', {key: '$keyRecord'})")
+
+        // to activate the log compaction process we publish dummy messages
+        db.execute("UNWIND range(1,9999) as id CALL streams.publish('$topic', 'id', {key: 'id'}) RETURN null") {
+            assertEquals(9999, Iterators.count(it))
+        }
+        // wait for messages population in topic
+        Thread.sleep(15000)
```
Comment (moxious) [inline producer/src/test/kotlin/streams/integrations/KafkaEventRouterLogCompactionTSE.kt:72]: your choice on how best to do this but my experience is whenever you have Thread.sleep in a test, the test ends up being flaky the one time kafka is too slow, or whatever.  Consider polling longer, until you get expected number of records.    This code pattern (Thread.sleep followed by poll) is repeated many times in these tests, you can refactor into a func to do it once in a more resilient way

File: producer/src/test/kotlin/streams/integrations/KafkaEventRouterLogCompactionTSE.kt [hunk 5]
```diff
@@ -0,0 +1,627 @@
...
+        db.execute("""
+            |MATCH (pippo:Person {name:'Pippo'})
+            |MATCH (pluto:Person {name:'Pluto'})
+            |MERGE (pippo)-[:KNOWS]->(pluto)
+        """.trimMargin())
+        db.execute("MATCH (:Person {name:'Pippo'})-[rel:KNOWS]->(:Person {name:'Pluto'}) DELETE rel")
+
+        // to activate the log compaction process we create dummy messages
+        createManyPersons()
+        Thread.sleep(20000)
```
Comment (moxious) [inline producer/src/test/kotlin/streams/integrations/KafkaEventRouterLogCompactionTSE.kt:104]: see poll note above

File: producer/src/test/kotlin/streams/integrations/KafkaEventRouterLogCompactionTSE.kt [hunk 6]
```diff
@@ -0,0 +1,627 @@
...
+            |MERGE (pippo)-[:KNOWS]->(pluto)
+        """.trimMargin())
+
+        // we delete the relation, so will be created a tombstone record
+        db.execute("MATCH (:Person {name:'Pippo'})-[rel:KNOWS]->(:Person {name:'Pluto'}) DELETE rel")
+        db.execute("CREATE (:Person {name:'Paperino'})")
+
+        // to activate the log compaction process we create dummy messages
+        createManyPersons()
+        Thread.sleep(20000)
```
Comment (moxious) [inline producer/src/test/kotlin/streams/integrations/KafkaEventRouterLogCompactionTSE.kt:142]: see poll note above

File: producer/src/test/kotlin/streams/integrations/KafkaEventRouterLogCompactionTSE.kt [hunk 7]
```diff
@@ -0,0 +1,627 @@
...
+
+        db.execute("CREATE (:Person {name:'Watson'})")
+        db.execute("CREATE (:Person {name:'Sherlock'})")
+        db.execute("MATCH (p:Person {name:'Sherlock'}) SET p.address = '221B Baker Street'")
+        // we delete a node, so will be created a tombstone record
+        db.execute("MATCH (p:Person {name:'Sherlock'}) DETACH DELETE p")
+
+        // to activate the log compaction process we create dummy messages and we waiting for message population
+        createManyPersons()
+        Thread.sleep(20000)
```
Comment (moxious) [inline producer/src/test/kotlin/streams/integrations/KafkaEventRouterLogCompactionTSE.kt:171]: see poll note above

File: producer/src/test/kotlin/streams/integrations/KafkaEventRouterLogCompactionTSE.kt [hunk 8]
```diff
@@ -0,0 +1,627 @@
...
+        kafkaConsumer.subscribe(listOf(topic))
+
+        db.execute("CREATE (:Person {name:'Watson'})")
+        db.execute("CREATE (:Person {name:'Sherlock'})")
+        db.execute("MATCH (p:Person {name:'Sherlock'}) SET p.address = '221B Baker Street'")
+
+        // to activate the log compaction process we create dummy messages and we waiting for message population
+        db.execute("MATCH (p:Person {name:'Sherlock'}) DETACH DELETE p")
+        createManyPersons()
+        Thread.sleep(20000)
```
Comment (moxious) [inline producer/src/test/kotlin/streams/integrations/KafkaEventRouterLogCompactionTSE.kt:197]: see poll note above

File: producer/src/test/kotlin/streams/integrations/KafkaEventRouterLogCompactionTSE.kt [hunk 9]
```diff
@@ -0,0 +1,627 @@
...
+                mapOf("streams.source.topic.nodes.${topic}" to "Person{*}")
+        )
+        kafkaConsumer.subscribe(listOf(topic))
+
+        assertFailsWith(TransactionFailureException::class, "Invalid kafka.streams.log.compaction.strategy value: $invalid") {
+            db.execute("CREATE (:Person {name:'Pippo'})")
+        }
+    }
+
+}
```
Comment (moxious) [inline producer/src/test/kotlin/streams/integrations/KafkaEventRouterLogCompactionTSE.kt:627]: really nice work with all of these tests 💯

**Review by moxious — CHANGES_REQUESTED** [review]

File: producer/src/test/kotlin/streams/integrations/KafkaEventRouterLogCompactionTSE.kt (hunk 4 above)
Comment (conker84) [reply producer/src/test/kotlin/streams/integrations/KafkaEventRouterLogCompactionTSE.kt:72]: @vga91 please switch to `assertEventually`

File: producer/src/main/kotlin/streams/Extensions.kt (hunk 1 above)
Comment (conker84) [reply producer/src/main/kotlin/streams/Extensions.kt:55]: @vga91 please add a check into the `validate` method of `KafkaConfiguration`

File: doc/docs/modules/ROOT/pages/producer-configuration.adoc (hunk 2 above)
Comment (vga91) [reply doc/docs/modules/ROOT/pages/producer-configuration.adoc:53]: I chose these two values to match the topic config `cleanup.policy` which has compact / delete values to enable log compaction or not. Of course, the term unique sounds good.
So, If you want, I can change `delete` to `unique`

Comment (moxious) [reply doc/docs/modules/ROOT/pages/producer-configuration.adoc:53]: I'm ok with the decision as it is, just make it clear in the docs.

Comment (vga91) [reply doc/docs/modules/ROOT/pages/producer-configuration.adoc:54]: Ok, i've added a note in the `.adoc`

File: doc/docs/modules/ROOT/pages/producer-configuration.adoc [hunk 10]
```diff
@@ -45,6 +46,13 @@ You can tune the custom property `kafka.topic.discovery.polling.interval` in ord
 periodically check for new topics into the Kafka cluster so the plugin will be able
 to send events to the defined topics.
 
+
+With `kafka.streams.log.compaction.strategy=delete` will be generated a sequence of unique keys with Neo4j Streams Source.
+instead with `kafka.streams.log.compaction.strategy=compact` the keys will be adapted to enable
+https://kafka.apache.org/documentation.html#compaction[Log Compaction] on the Kafka side.
+Please note that delete strategy does not actually delete records, it has this name  to match the topic config `cleanup.policy=delete/compact`.
+Namely, the operations which will involve the same nodes or relationships, will have the same key.
+
```
Comment (conker84) [inline doc/docs/modules/ROOT/pages/producer-configuration.adoc:55]: Please add the docs regarding the key structure for nodes and relationships for both use-case with/without unique contraints

**Review by conker84 — CHANGES_REQUESTED** [review]
Consider what we said in slack about improving the structure of the message keys.
Also add a test like `KafkaEventRouterEnterpriseTSE` that cover `NODE KEY` constraints

**Comment by moxious** [comment]
@conker84 to review & later merge

**Review by conker84 — CHANGES_REQUESTED** [review]

**Review by conker84 — APPROVED** [review]
LGTM thank you @vga91 !
