### PR TITLE
fixes #342: 4.1.(0, 1) cluster does not form in the presence of neo4j-streams-4.0.2.jar

### LINKED ISSUE #342: 4.1.(0, 1) cluster does not form in the presence of neo4j-streams-4.0.2.jar
## Actual Behavior (Mandatory)

See internal slack discussion involving dvoutila.   I independently reproduced this.  

## How to Reproduce the Problem

- Launch 4.1.0 cluster or 4.1.1
- Add neo4j-streams-4.0.2.jar.  
- With or without kafka/streams configuration in neo4j.conf, the same behavior will be seen, I did without any config (default neo4j.conf)
- Start the cluster, and then run a CREATE DATABASE command.
- Database is not created, and you will see lots of messages in the log like this:

```
2020-08-12 20:43:58.940+0000 INFO [c.n.c.c.s.CoreSnapshotService] [system] Waiting for another raft group member to publish a core state snapshot
```

## Hypothesis

Raft group for databases never properly form.   I don't see any evidence in the logs of anything bad that streams is doing, but this *related ticket* is a hint:  https://github.com/neo4j-contrib/neo4j-streams/issues/341 it appears that streams might be trying to subscribe to kafka topics or otherwise doing something with the kafka client, even in the absence of good configuration.

We've seen some issues lately where the database & cluster lifecycle is not appropriately respected by the internal availability guard.  That is to say, the DBMS may signal to plugins that a database is ready before the database is actually ready, causing streams to do something before the DBMS is ready for it.   So this is my hunch on where to look.   In particular, we need to look for code paths of how neo4j-streams becomes aware of new databases being created.  What actions does it take, and critically *when* in response to that?

## More Technical Information

(It may mention another database or the one you created, not necesarily the system database)

Behavior I'm seeing in a local cluster is that the raft group never properly forms.

One cluster member says this:

```
2020-08-12 21:49:42.358+0000 INFO [c.n.c.c.s.s.DurableStateStorage] [newdb] session-tracker state restored, up to ordinal -1
2020-08-12 21:49:42.364+0000 INFO [c.n.c.c.s.s.DurableStateStorage] [newdb] last-flushed state restored, up to ordinal -1
2020-08-12 21:49:42.367+0000 INFO [c.n.c.c.c.l.s.SegmentedRaftLog] [newdb] log started with recovered state State{prevIndex=-1, prevTerm=-1, appendIndex=-1}
2020-08-12 21:49:42.367+0000 INFO [c.n.c.c.c.m.RaftMembershipManager] [newdb] Membership state before recovery: RaftMembershipState{committed=null, appended=null, ordinal=-1}
2020-08-12 21:49:42.367+0000 INFO [c.n.c.c.c.m.RaftMembershipManager] [newdb] Recovering from: -1 to: -1
2020-08-12 21:49:42.367+0000 INFO [c.n.c.c.c.m.RaftMembershipManager] [newdb] Membership state after recovery: RaftMembershipState{committed=null, appended=null, ordinal=-1}
2020-08-12 21:49:42.368+0000 INFO [c.n.c.c.c.m.RaftMembershipManager] [newdb] Target membership: []
2020-08-12 21:49:42.368+0000 WARN [c.n.c.c.c.m.RaftMembershipManager] [newdb] Target membership [] does not contain a majority of existing raft members []. It is likely an operator removed too many core members too quickly. If not, this issue should be transient.
2020-08-12 21:49:42.388+0000 INFO [c.n.c.d.RaftMonitor] Trying bootstrap using initial members [MemberId{e10a7715}, MemberId{b1275961}, MemberId{6764dade}] and store ID StoreId{creationTime=1597268981712, randomId=-5020605660939756307, storeVersion=3471765337752883975, upgradeTime=1597268981712, upgradeTxId=-5020605660939756307}
2020-08-12 21:49:42.398+0000 INFO [c.n.c.c.s.RaftBootstrapper] [newdb] Bootstrapping database newdb for members [MemberId{e10a7715}, MemberId{b1275961}, MemberId{6764dade}]
2020-08-12 21:49:42.399+0000 INFO [c.n.c.c.s.RaftBootstrapper] [newdb] Initializing the store for database newdb using a temporary database in com.neo4j.causalclustering.core.TempBootstrapDir$Resource@33dcf233
2020-08-12 21:49:42.752+0000 INFO [c.n.c.d.a.GlobalTopologyState] Core topology for database DatabaseId{087b170c} is now: [MemberId{b1275961}, MemberId{6764dade}, MemberId{e10a7715}]
No members where lost
New members: 
  MemberId{6764dade}=CoreServerInfo{raftServer=10.142.0.105:7000, catchupServer=10.142.0.105:6000, connectorAddresses=bolt://35.243.139.186:7687,http://35.243.139.186:7474,https://35.243.139.186:7473, groups=[], startedDatabaseIds=[DatabaseId{cfb8387e}, DatabaseId{0f9b21e7}, DatabaseId{087b170c}, DatabaseId{00000000}], refuseToBeLeader=false}
  MemberId{e10a7715}=CoreServerInfo{raftServer=10.142.0.16:7000, catchupServer=10.142.0.16:6000, connectorAddresses=bolt://34.75.36.233:7687,http://34.75.36.233:7474,https://34.75.36.233:7473, groups=[], startedDatabaseIds=[DatabaseId{0f9b21e7}, DatabaseId{cfb8387e}, DatabaseId{087b170c}, DatabaseId{00000000}], refuseToBeLeader=false}
  MemberId{b1275961}=CoreServerInfo{raftServer=10.142.0.104:7000, catchupServer=10.142.0.104:6000, connectorAddresses=bolt://35.237.123.125:7687,http://35.237.123.125:7474,https://35.237.123.125:7473, groups=[], startedDatabaseIds=[DatabaseId{cfb8387e}, DatabaseId{0f9b21e7}, DatabaseId{087b170c}, DatabaseId{00000000}], refuseToBeLeader=false}
2020-08-12 21:49:42.753+0000 INFO [c.n.c.c.c.m.RaftMembershipManager] [newdb] Target membership: [MemberId{b1275961}, MemberId{6764dade}, MemberId{e10a7715}]
2020-08-12 21:49:42.753+0000 WARN [c.n.c.c.c.m.RaftMembershipManager] [newdb] Target membership [MemberId{e10a7715}, MemberId{b1275961}, MemberId{6764dade}] does not contain a majority of existing raft members []. It is likely an operator removed too many core members too quickly. If not, this issue should be transient.
2020-08-12 21:49:42.754+0000 WARN [c.n.c.c.c.m.RaftMembershipManager] [newdb] Target membership [MemberId{e10a7715}, MemberId{b1275961}, MemberId{6764dade}] does not contain a majority of existing raft members []. It is likely an operator removed too many core members too quickly. If not, this issue should be transient.
2020-08-12 21:51:07.807+0000 INFO [c.n.c.c.c.l.s.Segments] [system] Pruning SegmentFile{file=raft.log.0, header=SegmentHeader{formatVersion=2, recordOffset=56, prevFileLastIndex=-1, segmentNumber=0, prevIndex=-1, prevTerm=-1}}
2020-08-12 21:51:24.008+0000 INFO [c.n.c.c.c.l.s.Segments] [neo4j] Pruning SegmentFile{file=raft.log.0, header=SegmentHeader{formatVersion=2, recordOffset=56, prevFileLastIndex=-1, segmentNumber=0, prevIndex=-1, prevTerm=-1}}
2020-08-12 21:51:24.021+0000 INFO [c.n.c.c.c.l.s.Segments] [foo] Pruning SegmentFile{file=raft.log.0, header=SegmentHeader{formatVersion=2, recordOffset=56, prevFileLastIndex=-1, segmentNumber=0, prevIndex=-1, prevTerm=-1}}
```

the others say this:

```
2020-08-12 21:49:42.421+0000 INFO [c.n.c.d.RaftMonitor] Trying bootstrap using initial members [MemberId{e10a7715}, MemberId{b1275961}, MemberId{6764dade}] and store ID StoreId{creationTime=1597268981712, randomId=-5020605660939756307, storeVersion=3471765337752883975, upgradeTime=1597268981712, upgradeTxId=-5020605660939756307}
2020-08-12 21:49:42.430+0000 INFO [c.n.c.c.s.CoreSnapshotService] [newdb] Waiting for another raft group member to publish a core state snapshot
2020-08-12 21:49:42.824+0000 INFO [c.n.c.d.a.GlobalTopologyState] Core topology for database DatabaseId{087b170c} is now: [MemberId{b1275961}, MemberId{6764dade}, MemberId{e10a7715}]
No members where lost
New members: 
  MemberId{6764dade}=CoreServerInfo{raftServer=10.142.0.105:7000, catchupServer=10.142.0.105:6000, connectorAddresses=bolt://35.243.139.186:7687,http://35.243.139.186:7474,https://35.243.139.186:7473, groups=[], startedDatabaseIds=[DatabaseId{087b170c}, DatabaseId{00000000}, DatabaseId{0f9b21e7}, DatabaseId{cfb8387e}], refuseToBeLeader=false}
  MemberId{e10a7715}=CoreServerInfo{raftServer=10.142.0.16:7000, catchupServer=10.142.0.16:6000, connectorAddresses=bolt://34.75.36.233:7687,http://34.75.36.233:7474,https://34.75.36.233:7473, groups=[], startedDatabaseIds=[DatabaseId{cfb8387e}, DatabaseId{0f9b21e7}, DatabaseId{087b170c}, DatabaseId{00000000}], refuseToBeLeader=false}
  MemberId{b1275961}=CoreServerInfo{raftServer=10.142.0.104:7000, catchupServer=10.142.0.104:6000, connectorAddresses=bolt://35.237.123.125:7687,http://35.237.123.125:7474,https://35.237.123.125:7473, groups=[], startedDatabaseIds=[DatabaseId{cfb8387e}, DatabaseId{0f9b21e7}, DatabaseId{087b170c}, DatabaseId{00000000}], refuseToBeLeader=false}
2020-08-12 21:49:42.825+0000 INFO [c.n.c.c.c.m.RaftMembershipManager] [newdb] Target membership: [MemberId{b1275961}, MemberId{6764dade}, MemberId{e10a7715}]
2020-08-12 21:49:42.825+0000 WARN [c.n.c.c.c.m.RaftMembershipManager] [newdb] Target membership [MemberId{e10a7715}, MemberId{b1275961}, MemberId{6764dade}] does not contain a majority of existing raft members []. It is likely an operator removed too many core members too quickly. If not, this issue should be transient.
2020-08-12 21:49:42.826+0000 WARN [c.n.c.c.c.m.RaftMembershipManager] [newdb] Target membership [MemberId{e10a7715}, MemberId{b1275961}, MemberId{6764dade}] does not contain a majority of existing raft members []. It is likely an operator removed too many core members too quickly. If not, this issue should be transient.
2020-08-12 21:49:52.435+0000 INFO [c.n.c.c.s.CoreSnapshotService] [newdb] Waiting for another raft group member to publish a core state snapshot
2020-08-12 21:50:02.439+0000 INFO [c.n.c.c.s.CoreSnapshotService] [newdb] Waiting for another raft group member to publish a core state snapshot
2020-08-12 21:50:12.442+0000 INFO [c.n.c.c.s.CoreSnapshotService] [newdb] Waiting for another raft group member to publish a core state snapshot
2020-08-12 21:50:22.446+0000 INFO [c.n.c.c.s.CoreSnapshotService] [newdb] Waiting for another raft group member to publish a core state snapshot
2020-08-12 21:50:32.450+0000 INFO [c.n.c.c.s.CoreSnapshotService] [newdb] Waiting for another raft group member to publish a core state snapshot
```

### PR DESCRIPTION
**Pull request by conker84**
Fixes #342 

Even if we start the plugin in the `AvailabilityListner` in Neo4j 4.1.x the `system` db is not yet available. We need to wait until then is available.
*n.b.* the problem does not affect only clusters but also single instances in 4.1.1

## Proposed Changes (Mandatory)

A brief list of proposed changes in order to fix the issue:

  - Added a coroutine that waits until the `system` db is available in order to

### CODE REVIEW

File: consumer/src/main/kotlin/streams/kafka/KafkaEventSink.kt [hunk 1]
```diff
@@ -52,54 +55,56 @@ class KafkaEventSink(private val config: StreamsConfig,
...
-            this.errorService = KafkaErrorService(kafkaConfig.asProperties(),
-                    ErrorService.ErrorConfig.from(kafkaConfig.streamsSinkConfiguration.errorConfig),
-                    { s, e -> log.error(s,e as Throwable) })
-        }
-        return this.errorService
-    }
-
-    override fun start() { // TODO move to the abstract class
-        if (StreamsPluginStatus.RUNNING == status()) {
+    override fun start() = runBlocking { // TODO move to the abstract class
```
Comment (moxious) [inline consumer/src/main/kotlin/streams/kafka/KafkaEventSink.kt:71]: with stopping/restarting, probably need check for systemdb availability here, since it can go wrong & become unavailable during normal operations.

File: consumer/src/main/kotlin/streams/kafka/KafkaEventSink.kt [hunk 2]
```diff
@@ -52,54 +55,56 @@ class KafkaEventSink(private val config: StreamsConfig,
...
         log.info("Starting the Kafka Sink")
-        this.eventConsumer = getEventConsumerFactory()
-                .createStreamsEventConsumer(config, log)
-                .withTopics(topics) as KafkaEventConsumer
-        this.eventConsumer.start()
-        this.job = createJob()
+        mutex.withLock {
+            if (StreamsPluginStatus.RUNNING == status()) {
+                if (log.isDebugEnabled) {
+                    log.debug("Kafka Sink is already started.")
```
Comment (moxious) [inline consumer/src/main/kotlin/streams/kafka/KafkaEventSink.kt:94]: this check can go right at the top and shortcut out of the whole function.

File: consumer/src/main/kotlin/streams/kafka/KafkaEventSink.kt [hunk 3]
```diff
@@ -52,54 +55,56 @@ class KafkaEventSink(private val config: StreamsConfig,
...
+                }
+                return@runBlocking
+            }
+            try {
+                eventConsumer = getEventConsumerFactory()
+                        .createStreamsEventConsumer(config, log)
+                        .withTopics(topics) as KafkaEventConsumer
+                job = createJob()
+            } catch (e: Exception) {
+                log.error("Cannot create job because of the following exception:", e)
```
Comment (moxious) [inline consumer/src/main/kotlin/streams/kafka/KafkaEventSink.kt:104]: be more descriptive with this error:  what job?  What does it do?  What's the consequence?  If this error comes up, user needs to know what the consequence is.  (Probably that sink isn't working)

File: consumer/src/main/kotlin/streams/procedures/StreamsSinkProcedures.kt [hunk 4]
```diff
@@ -115,64 +132,58 @@ class StreamsSinkProcedures {
...
-        consumer.start()
-        val data = mutableListOf<Any>()
-        try {
-            val start = System.currentTimeMillis()
-            while ((System.currentTimeMillis() - start) < timeout) {
-                consumer.read(cfg) { _, topicData ->
-                    data.addAll(topicData.mapNotNull { it.value })
+        val data = ArrayBlockingQueue<StreamResult>(1000)
+        val tombstone = StreamResult(emptyMap<String, Any>())
+        GlobalScope.launch {
```
Comment (moxious) [inline consumer/src/main/kotlin/streams/procedures/StreamsSinkProcedures.kt:140]: this is just my lack of experience with kotlin but I don't understand most of this code block unfortunately.

**Review by moxious — COMMENTED** [review]
I followed most of this -- I may not be the best reviewer here, but offered a couple of thoughts.  I focused more heavily on the systemdb availability stuff, which was looking good.  

General question about this PR:  consider carefully the test coverage - I know events where the wrong lifecycle stuff happens are hard to test & reproduce.  Just make sure you're comforotable with the existing tests on the startup process, and lifecycle methods.

File: consumer/src/main/kotlin/streams/kafka/KafkaEventSink.kt (hunk 1 above)
Comment (conker84) [reply consumer/src/main/kotlin/streams/kafka/KafkaEventSink.kt:71]: Can it happen that with the database up&running the systemdb is not available?

File: consumer/src/main/kotlin/streams/kafka/KafkaEventSink.kt (hunk 2 above)
Comment (conker84) [reply consumer/src/main/kotlin/streams/kafka/KafkaEventSink.kt:94]: It need it here because is needs to be syncronized

File: consumer/src/main/kotlin/streams/kafka/KafkaEventSink.kt (hunk 3 above)
Comment (conker84) [reply consumer/src/main/kotlin/streams/kafka/KafkaEventSink.kt:104]: done

**Comment by voutilad** [comment]
Haven’t tested in a causal cluster yet, but single node this is working fine for me at the moment.
